baseURL: https://kashishsolanki.netlify.app/
languageCode: en-us
title: Kashish Solanki
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Know More
    subtitle: |-
      Here is my portfolio website released under the creative commons
    title: Kashish Yudhviram Solanki
  blog: {}
  contact:
    address:
      - city: London, NW1 6EW
        country: United Kingdom
        street: Westminister
        title: 38 Marys Court, 4 Palgrave Gardens
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ksolanki.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7878761401
        title: Phone
  custom_css: []
  custom_js: []
  description: 
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Kashish Yudhviram Solanki
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-github
        label: GitHub
        url: https://github.com/KashishSolanki16
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/kashishsolanki16/
  image: banner.JPG
  name: Kashish Solanki
  navigation:
    button1:
      - name: Explore
        url: blogs
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs/kashish
    menu: Menu
    subtitle: Portfolio Website
    title: Kashish Solanki
  tiles:
    enable: yes
    showcase:
      - image: pic02.jpg
        subtitle: Know More About Me
        title: About Me
        url: blogs/kashish
      - image: pic04.jpg  
        subtitle: Economics and Statistics | Analytics and Management |  
        title: Education and Work Experience
        url: blogs/workex
      - image: pic03.jpg
        subtitle: Piano | Travel | Formula One | Freestyle Dancing 
        title: Hobbies and Interests
        url: blogs/hobbies
      - image: pic05.jpg
        subtitle: Analysis of IMDB ratings
        title: IMDB Ratings Comparison - Spielberg and Burton
        url: blogs/project1
      - image: pic06.jpg
        subtitle: Animal rescue dataset
        title: London Fire Brigade
        url: blogs/project2
      - image: pic07.jpg
        subtitle: Climate Change and Temperature Anomalies 
        title: Climate Data Analysis
        url: blogs/project3
  two:
    buttonText: Click to View
    enable: yes
    subtitle: 
    title: Resume
    url: https://drive.google.com/file/d/1t30QDmrlnLumjmsS-M-iOweIYulPnc_U/view?usp=sharing